name: Сообщение об ошибке
description: Сообщить о воспроизводимой ошибке
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Описание
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Шаги воспроизведения
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Версия Python
    validations:
      required: true
  - type: checkboxes
    id: security
    attributes:
      label: Проверка
      options:
        - label: Я удалил токены и чувствительные данные
          required: true
